/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.quartos;

import controller.QuartoController;
import enums.CategoriaQuarto;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Quarto;

/**
 *
 * @author leoms
 */
public class GerenciarQuartoView extends javax.swing.JInternalFrame {

    
    private Integer linha = -1;
    
    public GerenciarQuartoView() {
        initComponents();
        preencherCombo();
        Inicializar();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNome = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jtxValor = new javax.swing.JTextField();
        jcbTipo = new javax.swing.JComboBox<CategoriaQuarto>();
        jbExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtQuartos = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jlIdFuncionario = new javax.swing.JLabel();
        jtxIdQuarto = new javax.swing.JTextField();

        jlNome.setText("Valor:");

        jlCargo.setText("Tipo:");

        jtxValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxValorActionPerformed(evt);
            }
        });

        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Valor", "Tipo"
            }
        ));
        jtQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtQuartosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtQuartos);

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jlIdFuncionario.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNome)
                            .addComponent(jlCargo)
                            .addComponent(jlIdFuncionario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdFuncionario)
                    .addComponent(jtxIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCargo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Inicializar(){
        jtxIdQuarto.setEditable(false);
        jtxValor.setEditable(false);
        jcbTipo.setEditable(false);
    }
    
    private void preencherTabela(){
        QuartoController controller = new QuartoController();
        List<Quarto> lista = controller.findAll();
        if (lista.isEmpty()) {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtQuartos.getModel();
            modeloTabela.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Nenhum Quarto Cadastrado", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtQuartos.getModel();
            modeloTabela.setRowCount(0);
            for (Quarto q: lista) {
                modeloTabela.addRow(new Object[]{ 
                    q.getIdQuarto(),
                    q.getValor(),
                    q.getCategoria()});
            }
        }
    }
    
    private void limparCampos(){
        jtxValor.setText("");
        jtxIdQuarto.setText("");
        jcbTipo.setSelectedIndex(0);
    }
    
    private void preencherCombo(){
        List<CategoriaQuarto> lista = Arrays.asList(CategoriaQuarto.values());
        for (CategoriaQuarto c: lista)
            jcbTipo.addItem(c);
    }
    
    private void jtxValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxValorActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Integer id = Integer.valueOf(jtxIdQuarto.getText());
        QuartoController controller = new QuartoController();
        controller.delete(id);
        JOptionPane.showMessageDialog(this, "Quarto excluído com Sucesso!");
        limparCampos();
        preencherTabela();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        String valor = jtxValor.getText();
        Integer id = Integer.valueOf(jtxIdQuarto.getText());
        CategoriaQuarto categoria = (CategoriaQuarto) jcbTipo.getSelectedItem();
        if ((valor.isEmpty()) || (categoria.getDescricao().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Digite todos os campos", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            Quarto quarto = new Quarto();
            quarto.setIdQuarto(id);
            quarto.setCategoria(categoria);
            quarto.setValor(Float.valueOf(valor.replace(",", ".")));
            QuartoController controller = new QuartoController();
            controller.edit(quarto);
            JOptionPane.showMessageDialog(this, "Quarto editado com Sucesso!");
            limparCampos();
            preencherTabela();
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtQuartosMouseClicked
        linha  = jtQuartos.getSelectedRow();
        if (linha != -1) {
            jtxIdQuarto.setText(jtQuartos.getValueAt(linha, 0).toString());
            jtxValor.setText(jtQuartos.getValueAt(linha, 1).toString());
            jcbTipo.setSelectedItem((CategoriaQuarto) jtQuartos.getValueAt(linha, 2));
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxIdQuarto.setEditable(false);
            jtxValor.setEditable(true);
            jcbTipo.setEditable(true);
            linha = -1;
        }
    }//GEN-LAST:event_jtQuartosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JComboBox<CategoriaQuarto> jcbTipo;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlIdFuncionario;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtQuartos;
    private javax.swing.JTextField jtxIdQuarto;
    private javax.swing.JTextField jtxValor;
    // End of variables declaration//GEN-END:variables
}
