/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.quartos;

import view.funcionarios.*;
import controller.FuncionarioController;
import controller.QuartoController;
import enums.CategoriaQuarto;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;
import model.Quarto;
import relatorios.Relatorio;

/**
 *
 * @author leoms
 */
public class RelatorioQuartoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarFuncionarioView
     */
    public RelatorioQuartoView() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtQuartos = new javax.swing.JTable();
        jbRelatorio = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcbTipo = new javax.swing.JComboBox<CategoriaQuarto>();

        jLabel1.setText("Tipo:");

        jtQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtQuartos);
        if (jtQuartos.getColumnModel().getColumnCount() > 0) {
            jtQuartos.getColumnModel().getColumn(0).setResizable(false);
            jtQuartos.getColumnModel().getColumn(1).setResizable(false);
            jtQuartos.getColumnModel().getColumn(2).setResizable(false);
        }

        jbRelatorio.setText("Gerar relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBuscar)
                        .addGap(9, 9, 9)
                        .addComponent(jbRelatorio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jbRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        CategoriaQuarto cat = (CategoriaQuarto) jcbTipo.getSelectedItem();
        QuartoController c = new QuartoController();
        List<Quarto> lista = c.findByCategoriaQuarto(cat);
        if(lista.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum quarto encontrado para o filtro");
            DefaultTableModel modeloTabela = (DefaultTableModel) jtQuartos.getModel();
            modeloTabela.setRowCount(0);
            return;
        }
        
        DefaultTableModel modeloTabela = (DefaultTableModel) jtQuartos.getModel();
        modeloTabela.setRowCount(0);
        for (Quarto q: lista) {
                modeloTabela.addRow(new Object[]{ 
                    q.getIdQuarto(),
                    q.getValor(),
                    q.getCategoria()});
            }
    }//GEN-LAST:event_jbBuscarActionPerformed
    
    private void preencherCombo(){
        List<CategoriaQuarto> lista = Arrays.asList(CategoriaQuarto.values());
        for (CategoriaQuarto c: lista)
            jcbTipo.addItem(c);
    }
    
    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        try {
            HashMap<String, Object> parametros = new HashMap<>();
            CategoriaQuarto cat = (CategoriaQuarto) jcbTipo.getSelectedItem();
            parametros.put("categoria", cat.getDescricao());
            Relatorio.gerarRelatorio("src/relatorios/RelQuartos", parametros);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JComboBox<CategoriaQuarto> jcbTipo;
    private javax.swing.JTable jtQuartos;
    // End of variables declaration//GEN-END:variables
}
