/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.estadia;

import controller.EstadiaController;
import controller.HospedeController;
import controller.QuartoController;
import controller.ServicoController;
import enums.CargoFuncionario;
import enums.TipoServico;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Estadia;
import model.Hospede;
import model.Quarto;
import model.Servico;

/**
 *
 * @author leoms
 */
public class GerenciarEstadiaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarFuncionarioView
     */
    
    private Integer linha = -1;
    
    public GerenciarEstadiaView() {
        initComponents();
        preencherComboQuartos();
        preencherComboHospedes();
        Inicializar();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jlId = new javax.swing.JLabel();
        jtxIdEstadia = new javax.swing.JTextField();
        jtxCheckin = new javax.swing.JFormattedTextField();
        jlCpf = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jcbQuartos = new javax.swing.JComboBox<Quarto>();
        jcbHospedes = new javax.swing.JComboBox<Hospede>();
        jlCargo1 = new javax.swing.JLabel();
        jlCpf1 = new javax.swing.JLabel();
        jtxCheckoutFinal = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstadias = new javax.swing.JTable();
        jlCpf2 = new javax.swing.JLabel();
        jtxCheckoutEsperado = new javax.swing.JFormattedTextField();

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jlId.setText("ID:");

        jtxIdEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdEstadiaActionPerformed(evt);
            }
        });

        jtxCheckin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y HH:mm:ss"))));
        jtxCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCheckinActionPerformed(evt);
            }
        });

        jlCpf.setText("Checkin:");

        jlCargo.setText("Quarto:");

        jcbQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbQuartosActionPerformed(evt);
            }
        });

        jcbHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHospedesActionPerformed(evt);
            }
        });

        jlCargo1.setText("Hóspede");

        jlCpf1.setText("Checkout (Esperado):");

        jtxCheckoutFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y HH:mm:ss"))));
        jtxCheckoutFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCheckoutFinalActionPerformed(evt);
            }
        });

        jtEstadias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Checkin", "Checkout (esperado)", "Checkout", "Quarto", "Hospede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEstadias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEstadiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEstadias);
        if (jtEstadias.getColumnModel().getColumnCount() > 0) {
            jtEstadias.getColumnModel().getColumn(0).setResizable(false);
            jtEstadias.getColumnModel().getColumn(1).setResizable(false);
            jtEstadias.getColumnModel().getColumn(2).setResizable(false);
            jtEstadias.getColumnModel().getColumn(3).setResizable(false);
            jtEstadias.getColumnModel().getColumn(4).setResizable(false);
            jtEstadias.getColumnModel().getColumn(5).setResizable(false);
        }

        jlCpf2.setText("Checkout:");

        jtxCheckoutEsperado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y HH:mm:ss"))));
        jtxCheckoutEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCheckoutEsperadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlId)
                .addGap(18, 18, 18)
                .addComponent(jtxIdEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCargo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbQuartos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jlCargo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbHospedes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpf1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCpf2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxCheckoutFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxCheckoutEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlId)
                            .addComponent(jtxIdEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxCheckoutFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpf2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf)
                            .addComponent(jtxCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpf1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtxCheckoutEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCargo)
                    .addComponent(jcbQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCargo1)
                    .addComponent(jcbHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Inicializar(){
        jtxIdEstadia.setEditable(false);
        jtxCheckin.setEditable(false);
        jtxCheckoutEsperado.setEditable(false);
        jtxCheckoutFinal.setEditable(false);
        jcbQuartos.setEnabled(false);
        jcbHospedes.setEnabled(false);        
    }
    
    private void preencherTabela(){
        EstadiaController controller = new EstadiaController();
        List<Estadia> lista = controller.findAll();
        if (lista.isEmpty()) {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtEstadias.getModel();
            modeloTabela.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Nenhuma Estadia Cadastrado", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtEstadias.getModel();
            modeloTabela.setRowCount(0);
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");            
            for (Estadia e: lista) {
                String strCheckoutFinal = "";
                if(e.getDtCheckoutFinal() != null){
                    strCheckoutFinal = format.format(e.getDtCheckoutFinal());
                }
                modeloTabela.addRow(new Object[]{
                    e.getIdEstadia(),                    
                    format.format(e.getDtCheckin()),
                    format.format(e.getDtCheckoutEsperado()),
                    strCheckoutFinal,
                    e.getQuarto(),
                    e.getHospede()});
            }
        }
    }
    
    private void limparCampos(){
        jtxIdEstadia.setText("");
        jtxCheckoutFinal.setText("");
        jtxCheckoutEsperado.setText("");
        jtxCheckin.setText("");
        jcbQuartos.setSelectedIndex(0);
        jcbHospedes.setSelectedIndex(0);
    }
    
    private void preencherComboQuartos(){
        QuartoController controller = new QuartoController();
        List<Quarto> lista = controller.findAll();
        for(Quarto q: lista)
            jcbQuartos.addItem(q);
    }
    
    private void preencherComboHospedes(){
        HospedeController controller = new HospedeController();
        List<Hospede> lista = controller.findAll();
        for (Hospede h: lista)
            jcbHospedes.addItem(h);
    }
    
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Integer id = Integer.valueOf(jtxIdEstadia.getText());
        EstadiaController controller = new EstadiaController();
        controller.delete(id);
        JOptionPane.showMessageDialog(this, "Estadia excluído com Sucesso!");
        limparCampos();
        preencherTabela();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        Integer id = Integer.valueOf(jtxIdEstadia.getText());
        String strDataCheckin = jtxCheckin.getText();
        String strDataCheckoutEsperado = jtxCheckoutEsperado.getText();           
        String strDataCheckoutFinal = jtxCheckoutFinal.getText(); 
        Quarto quarto = (Quarto) jcbQuartos.getSelectedItem();
        Hospede hospede = (Hospede) jcbHospedes.getSelectedItem();
        if ((strDataCheckin.isEmpty()) || (strDataCheckoutEsperado.isEmpty()) || (quarto == null) || hospede == null) {
            JOptionPane.showMessageDialog(this, "Digite todos os campos", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                EstadiaController controller = new EstadiaController();
                Estadia estadia = new Estadia();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                estadia.setDtCheckin(format.parse(strDataCheckin));
                estadia.setDtCheckoutEsperado(format.parse(strDataCheckoutEsperado));
                if(!strDataCheckoutFinal.isEmpty()){
                    estadia.setDtCheckoutFinal(format.parse(strDataCheckoutFinal));
                }
                estadia.setHospede(hospede);
                estadia.setQuarto(quarto);
                estadia.setIdEstadia(id);
                controller.edit(estadia);
                limparCampos();
                preencherTabela();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Serviço Inserido com Sucesso!");
            limparCampos();
            preencherTabela();
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtxIdEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdEstadiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdEstadiaActionPerformed

    private void jtxCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCheckinActionPerformed

    private void jcbQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbQuartosActionPerformed

    private void jcbHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHospedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHospedesActionPerformed

    private void jtxCheckoutFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCheckoutFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCheckoutFinalActionPerformed

    private void jtxCheckoutEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCheckoutEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCheckoutEsperadoActionPerformed

    private void jtEstadiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstadiasMouseClicked
        linha  = jtEstadias.getSelectedRow();
        if (linha != -1) {
            jtxIdEstadia.setText(jtEstadias.getValueAt(linha, 0).toString());
            jtxCheckin.setText(jtEstadias.getValueAt(linha, 1).toString());
            jtxCheckoutEsperado.setText(jtEstadias.getValueAt(linha, 2).toString());
            jtxCheckoutFinal.setText(jtEstadias.getValueAt(linha, 3).toString());
            jcbQuartos.setSelectedItem((Quarto) jtEstadias.getValueAt(linha, 4));
            jcbHospedes.setSelectedItem((Hospede) jtEstadias.getValueAt(linha, 5));
            jtxCheckin.setEditable(true);
            jtxCheckoutEsperado.setEditable(true);
            jtxCheckoutFinal.setEditable(true);
            jcbQuartos.setEnabled(true);
            jcbHospedes.setEnabled(true);   
            linha = -1;
        }
    }//GEN-LAST:event_jtEstadiasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JComboBox<Hospede> jcbHospedes;
    private javax.swing.JComboBox<Quarto> jcbQuartos;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCargo1;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpf1;
    private javax.swing.JLabel jlCpf2;
    private javax.swing.JLabel jlId;
    private javax.swing.JTable jtEstadias;
    private javax.swing.JFormattedTextField jtxCheckin;
    private javax.swing.JFormattedTextField jtxCheckoutEsperado;
    private javax.swing.JFormattedTextField jtxCheckoutFinal;
    private javax.swing.JTextField jtxIdEstadia;
    // End of variables declaration//GEN-END:variables

}
