/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.estadia;

import controller.EstadiaController;
import controller.QuartoController;
import controller.ServicoController;
import enums.TipoServico;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Estadia;
import model.Quarto;
import model.Servico;
import relatorios.Relatorio;

/**
 *
 * @author leoms
 */
public class RelatorioEstadiaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarFuncionarioView
     */
    public RelatorioEstadiaView() {
        initComponents();
        preencherComboQuartos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbRelatorio = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcbQuartos = new javax.swing.JComboBox<Quarto>();
        jlCargo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstadias = new javax.swing.JTable();

        jbRelatorio.setText("Gerar relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcbQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbQuartosActionPerformed(evt);
            }
        });

        jlCargo.setText("Quarto:");

        jtEstadias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Checkin", "Checkout (esperado)", "Checkout", "Quarto", "Hospede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEstadias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEstadiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEstadias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jlCargo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbQuartos, 0, 379, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRelatorio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCargo)
                    .addComponent(jcbQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jbRelatorio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        EstadiaController controller = new EstadiaController();
        Quarto q = (Quarto) jcbQuartos.getSelectedItem();
        List<Estadia> lista = controller.findByQuarto(q);
        if (lista.isEmpty()) {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtEstadias.getModel();
            modeloTabela.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Nenhuma Estadia Cadastrado", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtEstadias.getModel();
            modeloTabela.setRowCount(0);
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");            
            for (Estadia e: lista) {
                String strCheckoutFinal = "";
                if(e.getDtCheckoutFinal() != null){
                    strCheckoutFinal = format.format(e.getDtCheckoutFinal());
                }
                modeloTabela.addRow(new Object[]{
                    e.getIdEstadia(),                    
                    format.format(e.getDtCheckin()),
                    format.format(e.getDtCheckoutEsperado()),
                    strCheckoutFinal,
                    e.getQuarto(),
                    e.getHospede()});
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void preencherComboQuartos(){
        QuartoController controller = new QuartoController();
        List<Quarto> lista = controller.findAll();
        for(Quarto q: lista)
            jcbQuartos.addItem(q);
    }
    
    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        try {
            HashMap<String, Object> parametros = new HashMap<>();
            Quarto quarto = (Quarto) jcbQuartos.getSelectedItem();
            parametros.put("quartoId", quarto.getIdQuarto());
            Relatorio.gerarRelatorio("src/relatorios/RelEstadia", parametros);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jcbQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbQuartosActionPerformed

    private void jtEstadiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstadiasMouseClicked
    }//GEN-LAST:event_jtEstadiasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JComboBox<Quarto> jcbQuartos;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JTable jtEstadias;
    // End of variables declaration//GEN-END:variables
}
