/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import view.funcionarios.CadastrarFuncionarioView;
import view.funcionarios.GerenciarFuncionarioView;

/**
 *
 * @author leoms
 */
public class HomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeView.class.getName());

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    private void abrirOuFocarView(javax.swing.JInternalFrame viewParaAbrir) {
        for (javax.swing.JInternalFrame frame : areaDeTrabalho.getAllFrames()) {
            if (frame.getClass().equals(viewParaAbrir.getClass())) {
                try {
                    frame.setSelected(true);
                    frame.toFront();
                    return;
                } catch (java.beans.PropertyVetoException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao focar na janela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        areaDeTrabalho.add(viewParaAbrir);
        viewParaAbrir.setVisible(true);
        try {
            viewParaAbrir.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, "Erro ao exibir a janela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDeTrabalho = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmFuncionario = new javax.swing.JMenu();
        jmiCadastrarFunc = new javax.swing.JMenuItem();
        jmiGerenciarFunc = new javax.swing.JMenuItem();
        jmQuarto = new javax.swing.JMenu();
        jmiCadastrarQuar = new javax.swing.JMenuItem();
        jmEstadia = new javax.swing.JMenu();
        jmiCadastrarEsta = new javax.swing.JMenuItem();
        jmServicos = new javax.swing.JMenu();
        jmiCadastrarServ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTrabalho.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jmFuncionario.setText("Funcionários");

        jmiCadastrarFunc.setText("Cadastrar");
        jmiCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarFuncActionPerformed(evt);
            }
        });
        jmFuncionario.add(jmiCadastrarFunc);

        jmiGerenciarFunc.setText("Gerenciar");
        jmiGerenciarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarFuncActionPerformed(evt);
            }
        });
        jmFuncionario.add(jmiGerenciarFunc);

        jmbPrincipal.add(jmFuncionario);

        jmQuarto.setText("Quartos");

        jmiCadastrarQuar.setText("Cadastrar");
        jmQuarto.add(jmiCadastrarQuar);

        jmbPrincipal.add(jmQuarto);

        jmEstadia.setText("Estadias");

        jmiCadastrarEsta.setText("Cadastrar");
        jmEstadia.add(jmiCadastrarEsta);

        jmbPrincipal.add(jmEstadia);

        jmServicos.setText("Serviços");

        jmiCadastrarServ.setText("Cadastrar");
        jmServicos.add(jmiCadastrarServ);

        jmbPrincipal.add(jmServicos);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarFuncActionPerformed
        CadastrarFuncionarioView cadfuncview = new CadastrarFuncionarioView();
        abrirOuFocarView(cadfuncview);
    }//GEN-LAST:event_jmiCadastrarFuncActionPerformed

    private void jmiGerenciarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarFuncActionPerformed
        GerenciarFuncionarioView gerfuncview = new GerenciarFuncionarioView();
        abrirOuFocarView(gerfuncview);
    }//GEN-LAST:event_jmiGerenciarFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JMenu jmEstadia;
    private javax.swing.JMenu jmFuncionario;
    private javax.swing.JMenu jmQuarto;
    private javax.swing.JMenu jmServicos;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiCadastrarEsta;
    private javax.swing.JMenuItem jmiCadastrarFunc;
    private javax.swing.JMenuItem jmiCadastrarQuar;
    private javax.swing.JMenuItem jmiCadastrarServ;
    private javax.swing.JMenuItem jmiGerenciarFunc;
    // End of variables declaration//GEN-END:variables
}
