/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import view.estadia.CadastrarEstadiaView;
import view.estadia.GerenciarEstadiaView;
import view.estadia.RelatorioEstadiaView;
import view.funcionarios.CadastrarFuncionarioView;
import view.funcionarios.GerenciarFuncionarioView;
import view.funcionarios.RelatorioFuncionarioView;
import view.hospede.CadastrarHospedeView;
import view.hospede.GerenciarHospedeView;
import view.quartos.CadastrarQuartoView;
import view.quartos.GerenciarQuartoView;
import view.quartos.RelatorioQuartoView;
import view.servicos.CadastrarServicoView;
import view.servicos.GerenciarServicoView;
import view.servicos.RelatorioServicoView;

/**
 *
 * @author leoms
 */
public class HomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeView.class.getName());

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    private void abrirOuFocarView(javax.swing.JInternalFrame viewParaAbrir) {
        for (javax.swing.JInternalFrame frame : areaDeTrabalho.getAllFrames()) {
            if (frame.getClass().equals(viewParaAbrir.getClass())) {
                try {
                    frame.setSelected(true);
                    frame.toFront();
                    return;
                } catch (java.beans.PropertyVetoException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao focar na janela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                frame.dispose();
            }
        }

        areaDeTrabalho.setPreferredSize(viewParaAbrir.getBounds().getSize());
        areaDeTrabalho.revalidate();
        viewParaAbrir.pack();
        areaDeTrabalho.add(viewParaAbrir);
        viewParaAbrir.setVisible(true);
        try {
            viewParaAbrir.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, "Erro ao exibir a janela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDeTrabalho = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmFuncionario = new javax.swing.JMenu();
        jmiCadastrarFunc = new javax.swing.JMenuItem();
        jmiGerenciarFunc = new javax.swing.JMenuItem();
        jmiRelatorioFunc = new javax.swing.JMenuItem();
        jmQuarto = new javax.swing.JMenu();
        jmiCadastrarQuar = new javax.swing.JMenuItem();
        jmiGerenciarQuar = new javax.swing.JMenuItem();
        jmiRelatorioQuar = new javax.swing.JMenuItem();
        jmHospede = new javax.swing.JMenu();
        jmiCadastrarHosp = new javax.swing.JMenuItem();
        jmiGerenciarHosp = new javax.swing.JMenuItem();
        jmEstadia = new javax.swing.JMenu();
        jmiCadastrarEsta = new javax.swing.JMenuItem();
        jmiGerenciarEsta = new javax.swing.JMenuItem();
        jmiRelatorioEsta = new javax.swing.JMenuItem();
        jmServicos = new javax.swing.JMenu();
        jmiCadastrarServ = new javax.swing.JMenuItem();
        jmiGerenciarServ = new javax.swing.JMenuItem();
        jmiRelatorioServ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTrabalho.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jmFuncionario.setText("Funcionários");

        jmiCadastrarFunc.setText("Cadastrar");
        jmiCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarFuncActionPerformed(evt);
            }
        });
        jmFuncionario.add(jmiCadastrarFunc);

        jmiGerenciarFunc.setText("Gerenciar");
        jmiGerenciarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarFuncActionPerformed(evt);
            }
        });
        jmFuncionario.add(jmiGerenciarFunc);

        jmiRelatorioFunc.setText("Relatório");
        jmiRelatorioFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioFuncActionPerformed(evt);
            }
        });
        jmFuncionario.add(jmiRelatorioFunc);

        jmbPrincipal.add(jmFuncionario);

        jmQuarto.setText("Quartos");

        jmiCadastrarQuar.setText("Cadastrar");
        jmiCadastrarQuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarQuarActionPerformed(evt);
            }
        });
        jmQuarto.add(jmiCadastrarQuar);

        jmiGerenciarQuar.setText("Gerenciar");
        jmiGerenciarQuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarQuarActionPerformed(evt);
            }
        });
        jmQuarto.add(jmiGerenciarQuar);

        jmiRelatorioQuar.setText("Relatório");
        jmiRelatorioQuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioQuarActionPerformed(evt);
            }
        });
        jmQuarto.add(jmiRelatorioQuar);

        jmbPrincipal.add(jmQuarto);

        jmHospede.setText("Hospede");

        jmiCadastrarHosp.setText("Cadastrar");
        jmiCadastrarHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarHospActionPerformed(evt);
            }
        });
        jmHospede.add(jmiCadastrarHosp);

        jmiGerenciarHosp.setText("Gerenciar");
        jmiGerenciarHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarHospActionPerformed(evt);
            }
        });
        jmHospede.add(jmiGerenciarHosp);

        jmbPrincipal.add(jmHospede);

        jmEstadia.setText("Estadias");

        jmiCadastrarEsta.setText("Cadastrar");
        jmiCadastrarEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarEstaActionPerformed(evt);
            }
        });
        jmEstadia.add(jmiCadastrarEsta);

        jmiGerenciarEsta.setText("Gerenciar");
        jmiGerenciarEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarEstaActionPerformed(evt);
            }
        });
        jmEstadia.add(jmiGerenciarEsta);

        jmiRelatorioEsta.setText("Relatório");
        jmiRelatorioEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioEstaActionPerformed(evt);
            }
        });
        jmEstadia.add(jmiRelatorioEsta);

        jmbPrincipal.add(jmEstadia);

        jmServicos.setText("Serviços");

        jmiCadastrarServ.setText("Cadastrar");
        jmiCadastrarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarServActionPerformed(evt);
            }
        });
        jmServicos.add(jmiCadastrarServ);

        jmiGerenciarServ.setText("Gerenciar");
        jmiGerenciarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerenciarServActionPerformed(evt);
            }
        });
        jmServicos.add(jmiGerenciarServ);

        jmiRelatorioServ.setText("Relatório");
        jmiRelatorioServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioServActionPerformed(evt);
            }
        });
        jmServicos.add(jmiRelatorioServ);

        jmbPrincipal.add(jmServicos);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarFuncActionPerformed
        CadastrarFuncionarioView cadfuncview = new CadastrarFuncionarioView();
        abrirOuFocarView(cadfuncview);
    }//GEN-LAST:event_jmiCadastrarFuncActionPerformed

    private void jmiGerenciarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarFuncActionPerformed
        GerenciarFuncionarioView gerfuncview = new GerenciarFuncionarioView();
        abrirOuFocarView(gerfuncview);
    }//GEN-LAST:event_jmiGerenciarFuncActionPerformed
    private void jmiRelatorioFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioFuncActionPerformed
        RelatorioFuncionarioView relfuncview = new RelatorioFuncionarioView();
        abrirOuFocarView(relfuncview);
    }//GEN-LAST:event_jmiRelatorioFuncActionPerformed

    private void jmiGerenciarQuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarQuarActionPerformed
        GerenciarQuartoView gerquarview = new GerenciarQuartoView();
        abrirOuFocarView(gerquarview);
    }//GEN-LAST:event_jmiGerenciarQuarActionPerformed

    private void jmiCadastrarQuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarQuarActionPerformed
        CadastrarQuartoView cadquarview = new CadastrarQuartoView();
        abrirOuFocarView(cadquarview);
    }//GEN-LAST:event_jmiCadastrarQuarActionPerformed

    private void jmiRelatorioQuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioQuarActionPerformed
        RelatorioQuartoView relquarview = new RelatorioQuartoView();
        abrirOuFocarView(relquarview);
    }//GEN-LAST:event_jmiRelatorioQuarActionPerformed

    private void jmiCadastrarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarServActionPerformed
        CadastrarServicoView cadservview = new CadastrarServicoView();
        abrirOuFocarView(cadservview);
    }//GEN-LAST:event_jmiCadastrarServActionPerformed

    private void jmiGerenciarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarServActionPerformed
        GerenciarServicoView gerservview = new GerenciarServicoView();
        abrirOuFocarView(gerservview);
    }//GEN-LAST:event_jmiGerenciarServActionPerformed

    private void jmiRelatorioServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioServActionPerformed
        RelatorioServicoView relservview = new RelatorioServicoView();
        abrirOuFocarView(relservview);
    }//GEN-LAST:event_jmiRelatorioServActionPerformed

    private void jmiCadastrarHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarHospActionPerformed
        CadastrarHospedeView cadhospview = new CadastrarHospedeView();
        abrirOuFocarView(cadhospview);
    }//GEN-LAST:event_jmiCadastrarHospActionPerformed

    private void jmiGerenciarHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarHospActionPerformed
        GerenciarHospedeView gerhospview = new GerenciarHospedeView();
        abrirOuFocarView(gerhospview);
    }//GEN-LAST:event_jmiGerenciarHospActionPerformed

    private void jmiGerenciarEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerenciarEstaActionPerformed
        GerenciarEstadiaView gerestaview = new GerenciarEstadiaView();
        abrirOuFocarView(gerestaview);
    }//GEN-LAST:event_jmiGerenciarEstaActionPerformed

    private void jmiCadastrarEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarEstaActionPerformed
        CadastrarEstadiaView cadestaview = new CadastrarEstadiaView();
        abrirOuFocarView(cadestaview);
    }//GEN-LAST:event_jmiCadastrarEstaActionPerformed

    private void jmiRelatorioEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioEstaActionPerformed
        RelatorioEstadiaView relestaview = new RelatorioEstadiaView();
        abrirOuFocarView(relestaview);
    }//GEN-LAST:event_jmiRelatorioEstaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JMenu jmEstadia;
    private javax.swing.JMenu jmFuncionario;
    private javax.swing.JMenu jmHospede;
    private javax.swing.JMenu jmQuarto;
    private javax.swing.JMenu jmServicos;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiCadastrarEsta;
    private javax.swing.JMenuItem jmiCadastrarFunc;
    private javax.swing.JMenuItem jmiCadastrarHosp;
    private javax.swing.JMenuItem jmiCadastrarQuar;
    private javax.swing.JMenuItem jmiCadastrarServ;
    private javax.swing.JMenuItem jmiGerenciarEsta;
    private javax.swing.JMenuItem jmiGerenciarFunc;
    private javax.swing.JMenuItem jmiGerenciarHosp;
    private javax.swing.JMenuItem jmiGerenciarQuar;
    private javax.swing.JMenuItem jmiGerenciarServ;
    private javax.swing.JMenuItem jmiRelatorioEsta;
    private javax.swing.JMenuItem jmiRelatorioFunc;
    private javax.swing.JMenuItem jmiRelatorioQuar;
    private javax.swing.JMenuItem jmiRelatorioServ;
    // End of variables declaration//GEN-END:variables
}
