/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.servicos;

import controller.HospedeController;
import controller.ServicoController;
import enums.TipoServico;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Hospede;
import model.Servico;

/**
 *
 * @author leoms
 */
public class CadastrarServicoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarFuncionarioView
     */
    public CadastrarServicoView() {
        initComponents();
        preencherComboServicos();
        preencherComboHospedes();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jtxValor = new javax.swing.JTextField();
        jtxData = new javax.swing.JFormattedTextField();
        jcbServicos = new javax.swing.JComboBox<TipoServico>();
        jbSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtServicos = new javax.swing.JTable();
        jlCargo1 = new javax.swing.JLabel();
        jcbHospedes = new javax.swing.JComboBox<Hospede>();

        jlNome.setText("Valor:");

        jlCpf.setText("Data:");

        jlCargo.setText("Serviço");

        jtxValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxValorActionPerformed(evt);
            }
        });

        jtxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y HH:mm:ss"))));
        jtxData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDataActionPerformed(evt);
            }
        });

        jcbServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbServicosActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jtServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serviço", "Valor", "Hóspede", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtServicos);
        if (jtServicos.getColumnModel().getColumnCount() > 0) {
            jtServicos.getColumnModel().getColumn(0).setResizable(false);
            jtServicos.getColumnModel().getColumn(1).setResizable(false);
            jtServicos.getColumnModel().getColumn(2).setResizable(false);
            jtServicos.getColumnModel().getColumn(3).setResizable(false);
        }

        jlCargo1.setText("Hóspede");

        jcbHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHospedesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jlCargo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jlCargo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbHospedes, 0, 206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jlCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxData)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf)
                    .addComponent(jtxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCargo)
                    .addComponent(jcbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCargo1)
                    .addComponent(jcbHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preencherTabela(){
        ServicoController controller = new ServicoController();
        List<Servico> lista = controller.findAll();
        if (lista.isEmpty()) {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtServicos.getModel();
            modeloTabela.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Nenhum Serviço Cadastrado", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel modeloTabela = (DefaultTableModel) jtServicos.getModel();
            modeloTabela.setRowCount(0);
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");            
            for (Servico s: lista) {
                modeloTabela.addRow(new Object[]{ 
                    s.getTipo(),
                    s.getValor(),
                    s.getHospede(),
                    format.format(s.getDtServico())});
            }
        }
    }
    
    private void limparCampos(){
        jtxValor.setText("");
        jtxData.setText("");
        jcbServicos.setSelectedIndex(0);
        jcbHospedes.setSelectedIndex(0);
    }
    
    private void preencherComboServicos(){
        List<TipoServico> lista = Arrays.asList(TipoServico.values());
        for (TipoServico t: lista)
            jcbServicos.addItem(t);
    }
    
    private void preencherComboHospedes(){
        HospedeController controller = new HospedeController();
        List<Hospede> lista = controller.findAll();
        for (Hospede h: lista)
            jcbHospedes.addItem(h);
    }
    
    private void jtxValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxValorActionPerformed

    private void jtxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDataActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        String valor = jtxValor.getText();
        String strData = jtxData.getText();               
        TipoServico tpServico = (TipoServico) jcbServicos.getSelectedItem();
        Hospede hospede = (Hospede) jcbHospedes.getSelectedItem();
        if ((valor.isEmpty()) || (strData.isEmpty()) || (tpServico.getDescricao().isEmpty()) || hospede == null) {
            JOptionPane.showMessageDialog(this, "Digite todos os campos", "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                ServicoController controller = new ServicoController();
                Servico servico = new Servico();
                servico.setTipo(tpServico);
                servico.setHospede(hospede);
                servico.setValor(Float.valueOf(valor.replace(",", ".")));
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");            
                Date data = format.parse(strData);
                servico.setDtServico(data);
                controller.insert(servico);
                limparCampos();
                preencherTabela();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Serviço Inserido com Sucesso!");
            limparCampos();
            preencherTabela();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jcbServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbServicosActionPerformed

    private void jcbHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHospedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHospedesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<Hospede> jcbHospedes;
    private javax.swing.JComboBox<TipoServico> jcbServicos;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCargo1;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtServicos;
    private javax.swing.JFormattedTextField jtxData;
    private javax.swing.JTextField jtxValor;
    // End of variables declaration//GEN-END:variables
}
